### ISSUE TITLE
You can get random loot in titan's runes slots (Act 4)

### ISSUE THREAD

**Issue by andrew-sadunenko** [thehambeard/RandomEquipment#4]
Steps to reproduce:
1. Get to Alushinyrra
2. Open any slot for titan rune (In my case, I received random loot from the slot shown in the screenshots)

![rebug0](https://github.com/thehambeard/RandomEquipment/assets/23294068/a5c303fe-a43f-475a-9ced-d2386333b4f7)
![rebug1](https://github.com/thehambeard/RandomEquipment/assets/23294068/68f493bb-3530-44d7-940f-78c6ff002c1d)

**Comment by thehambeard** [comment]
Will address. I completely forgot about those lootpart interactions like those and the puzzle pieces. Thanks for the heads up.

**Comment by thehambeard** [comment]
Could you test again with new release? If not working could you provide a save? I teleported there but it appears when you do that interactions don't load in properly?

**Comment by andrew-sadunenko** [comment]
I have tested 2.0.4 version, rune slots works fine now.

However, I've spotted a few more problematic containers where you can get random loot from (see screenshots):

1. Exploded enemy corpses (bone piles).
2. Midnight bolts.
3. Notes and books.

I can provide you save files for these cases if you want, but in order to load them you'll need to install some mods that my save files depends on. I don't have any "independent" save files right now unfortunately.

![rebug2](https://github.com/thehambeard/RandomEquipment/assets/23294068/c728fea7-93a5-413d-bac6-48df549be060)
![rebug3](https://github.com/thehambeard/RandomEquipment/assets/23294068/2f3f8fe7-4963-4abc-ab2e-3480a2d11ecf)

**Comment by thehambeard** [comment]
I did notice the notes and books last night. I thought the enemy was taken care of. I didn't really have a problem with it adding random loot to enemy corpses but it was attempting with any dropped loot even player dropped. I added a check for IsPlayerDropped but it seemed to consider everything you killed player dropped...

**Comment by thehambeard** [comment]
Should be mostly fixed. As long as notes and books are marked by OwlCat as the Environment type they will be skipped. I am sure some of them are marked as default though.

**Comment by thehambeard** [comment]
Fixed per: https://github.com/thehambeard/RandomEquipment/releases/tag/2.0.6
