### ISSUE TITLE
Options section of ModMenu is blank

### ISSUE THREAD

**Issue by Kilthak** [thehambeard/RandomEquipment#6]
When trying to select settings in the mod menu, I get the word "Options" in blue, and nothing else below it.  Additionally, the game logs in the tracker all the random equipment rolls, despite your description saying that it is off by default.  Attached is a screenshot of my mod menu list.
![Screenshot 2023-10-06 121416](https://github.com/thehambeard/RandomEquipment/assets/129162567/f9d3f408-8acc-45d4-9f9b-9e3a27178024)

**Comment by thehambeard** [comment]
The options are in mod menu. You can get there by going to the settings menu in game, not UMM. Ensure mod menu is up to date.

**Comment by thehambeard** [comment]
And verbose logging to player.Log file is off by default. Logging to combat log is on.

**Comment by Kilthak** [comment]
I literally gave you a screen shot of trying to use Mod Menu within the game...

**Comment by thehambeard** [comment]
I literally just told you that isn't where the settings are. That is Unity Mod Manager not the in game settings menu. Go to Options menu in game, just as you would to change graphics, sound, and other settings. Mod Menu is a separate mod that adds settings using the in game settings system.

**Comment by thehambeard** [comment]
https://github.com/WittleWolfie/ModMenu

**Comment by Kilthak** [comment]
ok, thank you, I found it
