### ISSUE TITLE
Integration with ModFinder

### ISSUE THREAD

**Issue by biship** [thehambeard/RandomEquipment#7]
Great mod, thank you for the update.
Able to add ModFinder integration?
It's very straight forward:
https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder
Thanks!

**Comment by thehambeard** [comment]
https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder/pull/72

I already did back in September?

**Comment by biship** [comment]
Oh you're right, I see it. My mistake!
