### ISSUE TITLE
The Narrow Path amulet seems broken - applying negative levels when hitting CE enemies

### ISSUE THREAD

**Issue by TwentyGaugeHigh** [thehambeard/RandomEquipment#8]
I don't know if this is the item specifically or if its a conflict with another mod by chance, but The Narrow Path amulet applied a negative level when my neutral good KC attacked a chaotic evil ghoul cleric.

Additionally, the amulet only applies half the AC from the description. My understanding is that it applies an untyped 2 AC bonus, and then another untyped 2AC bonus vs. evil enemies, but only the latter half is being applied.

I am uncertain if this is within the scope of the mod, but I felt it warranted a report. So far, all other items I've used from the mod are working as intended. This is the only one that seems to have an issue, at least that I've encountered.

![narrow_path](https://github.com/thehambeard/RandomEquipment/assets/101301548/545d30cb-0101-4c0c-8246-f8c21991eaee)
![narrow_path_2](https://github.com/thehambeard/RandomEquipment/assets/101301548/723d86be-886b-4e55-8fb8-2d23f0e4ea34)

**Comment by thehambeard** [comment]
![image](https://github.com/thehambeard/RandomEquipment/assets/61787444/ec31aca1-ff6c-4157-ba83-c359162dc4bd)
Looks to me like the amulet is setup as it should be.  Random Equipment does not edit any blueprints currently. This would be an issue outside of the mod.  I'll take a closer look at it though and if I see the same thing then I'll remove it from the list.  Thank you for reporting.
